### ISSUE TITLE
pip installs wrong dependency

### ISSUE THREAD

**Issue by minhajul-clarifai** [Clarifai/clarifai-python-utils#27]
## Issue
When trying to install the package with `pip install -U clarifai`, the following wrong library gets installed `clarifai==2.6.2`
This library points to a deprecated repo: https://github.com/Clarifai/clarifai-python

## Expected Output
Install `clarifai-python-utils==9.0.0` correctly

## Steps to recreate
1. Create new venv
2. Try installing clarifai-python-utils using the command specified in readme `pip install -U clarifai`

**Comment by yangshengBE** [comment]
we released this recently. If you install with `pip install -U clarifai`, you should get this one installed now.
