### ISSUE TITLE
pip install does not download clarifai/modules/style.css 

### ISSUE THREAD

**Issue by ghost** [Clarifai/clarifai-python-utils#42]
# Issue
When installing 9.3.3 or 9.3.0, `clarifai/modules/style.css` does not get installed resulting to an error

# Expected Output
New package versions to download `clarifai/modules/style.css`

# Steps to recreate
- Create new venv
- Test `ClarifaiStreamlitCSS.insert_default_css(st)`
```python
import streamlit as st
from clarifai.auth.helper import ClarifaiAuthHelper
from clarifai.modules.css import ClarifaiStreamlitCSS

# Set page layout
st.set_page_config(layout="wide")

# Use Clarifai CSS template
ClarifaiStreamlitCSS.insert_default_css(st)
```

![image](https://user-images.githubusercontent.com/110637701/234317019-d5383d27-da9b-43f0-899a-46f9b7c77332.png)

**Comment by yangshengBE** [comment]
should have been fixed.
